# Generated by Erlang.mk. Edit at your own risk!

src/lesson2_task07.erl:: src/lesson2_task05.erl; @touch $@
src/lesson2_task08.erl:: src/lesson2_task05.erl; @touch $@
src/lesson2_task09.erl:: src/lesson2_task05.erl; @touch $@
src/lesson2_task10.erl:: src/lesson2_task05.erl; @touch $@
src/lesson2_task11.erl:: src/lesson2_task05.erl; @touch $@
src/lesson2_task12.erl:: src/lesson2_task05.erl src/lesson2_task07.erl src/lesson2_task15.erl; @touch $@
src/lesson2_task13.erl:: src/lesson2_task12.erl; @touch $@
src/lesson2_task14.erl:: src/lesson2_task15.erl; @touch $@
src/lesson2_task15.erl:: src/lesson2_task05.erl src/lesson2_task07.erl; @touch $@

COMPILE_FIRST += lesson2_task05 lesson2_task07 lesson2_task15 lesson2_task12
